services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres:John%40Alustudent1@db.fxigmaaeoqeqjszucosw.supabase.co:5432/postgres
      - key: ADMIN_USERNAME
        value: dengjohn200@gmail.com
      - key: ADMIN_PASSWORD
        value: John@Alustudent1
      - key: SECRET_KEY
        value: your-secret-key-here